language: node_js
node_js:
- '8.9.4'
install:
- npm install
deploy:
- provider: npm
  email: 128techadmin@128technology.com
  skip_cleanup: true
  api_key:
    secure: UhYYIh9mh77VyXKcfm+unHzqRykn6xHpfsULT2cLnKUvhkUM6zSYCqHJ4ie8sUs8A6g/SKHb+6VUH2JFM9k/UU14OE9uiWfCRW9y9f2M75XkFKF9GtKTkYVfI8l8mHp1SFb7D0S29l2VVC3nwO2wMJw5wauLB6I49WvEL9Njb7hKdJv+ZidfhH8qgCCCmhg+GxU40HfktPdXDYS1gpjYJ7Gni7ScXmHjCCPICGaOmhf3hC/Ljl6x0EYsT0rK3qyJrTkqYyC5XPiIxzdyRkX3vEh14XWFd7ykoFr2s/AaGe261TKws7MNgACquqsFNz1h8mJ3SSn/+L8KbIhEC0lmo1KvOEOf0eJElr+0peCfH2ArVxOXoFzzLvuXqFkRqqmzNmFNk6xjyBzLbpPSFoSGsSMRjqnXgRKp6YLjbchNUOHTNEXP53VkFtWorS5mBrKVtGD4HUyXWRiQUQ6fD2Heckl5YTRSCQMoJ6NdLc7xk73RmYwQunbXP20wiHf748k1h9BhZziVzo7uG2uy//Jn0gSz8Hk8rTIQPBxsZcjkTgRyRwQwt2dajYUNlFYWIGSOE89X0eHuSJtdqdSckSOBBKNvNQTJRgzok9C0ZKpub5MubRTZJvkoAJp8OeOvMLA2sjGwn1GBU0SBG8EB1JXdPp/3+AZUHcaKAZH3nyWnj6I=
  on:
    repo: 128technology/128t-icons
    branch: master